define (require, exports, module)->
  '1':
    'id': '1-1'
    'no': '1'
    'area': '1'
    'name': '函館'
    'star': '1'
    'resource': '-'
    'max_lv': '11'
    'sence': ''
  '2':
    'id': '1-2'
    'no': '2'
    'area': '1'
    'name': '会津'
    'star': '1'
    'resource': '木炭'
    'max_lv': '12'
    'sence': ''
  '3':
    'id': '1-3'
    'no': '3'
    'area': '1'
    'name': '宇都宮'
    'star': '1'
    'resource': '砥石'
    'max_lv': '13'
    'sence': ''
  '4':
    'id': '1-4'
    'no': '4'
    'area': '1'
    'name': '鳥羽'
    'star': '2'
    'resource': '木炭・冷却材'
    'max_lv': '20'
    'sence': ''
  '5':
    'id': '2-1'
    'no': '5'
    'area': '2'
    'name': '鳥羽'
    'star': '1'
    'resource': '玉鋼・砥石'
    'max_lv': '23'
    'sence': ''
  '6':
    'id': '2-2'
    'no': '6'
    'area': '2'
    'name': '江戸'
    'star': '1'
    'resource': '木炭'
    'max_lv': '26'
    'sence': ''
  '7':
    'id': '2-3'
    'no': '7'
    'area': '2'
    'name': '江戸(元禄)'
    'star': '2'
    'resource': '冷却材'
    'max_lv': '29'
    'sence': ''
  '8':
    'id': '2-4'
    'no': '8'
    'area': '2'
    'name': '江戸(大坂冬の陣)'
    'star': '2'
    'resource': '依頼札'
    'max_lv': '32'
    'sence': ''
  '9':
    'id': '3-1'
    'no': '9'
    'area': '3'
    'name': '関ヶ原'
    'star': '2'
    'resource': '砥石'
    'max_lv': '40'
    'sence': ''
  '10':
    'id': '3-2'
    'no': '10'
    'area': '3'
    'name': '本能寺'
    'star': '2'
    'resource': '玉鋼・依頼札'
    'max_lv': '42'
    'sence': ''
  '11':
    'id': '3-3'
    'no': '11'
    'area': '3'
    'name': '越前'
    'star': '2'
    'resource': '木炭・玉鋼'
    'max_lv': '47'
    'sence': ''
  '12':
    'id': '3-4'
    'no': '12'
    'area': '3'
    'name': '安土'
    'star': '3'
    'resource': '砥石・依頼札'
    'max_lv': '51'
    'sence': ''
  '13':
    'id': '4-1'
    'no': '13'
    'area': '4'
    'name': '長篠'
    'star': '2'
    'resource': '冷却材、依頼札'
    'max_lv': '55'
    'sence': ''
  '14':
    'id': '4-2'
    'no': '14'
    'area': '4'
    'name': '三方ヶ原'
    'star': '3'
    'resource': '砥石'
    'max_lv': '59'
    'sence': ''
  '15':
    'id': '4-3'
    'no': '15'
    'area': '4'
    'name': '桶狭間'
    'star': '3'
    'resource': '木炭、冷却材、玉鋼'
    'max_lv': '63'
    'sence': ''
  '16':
    'id': '4-4'
    'no': '16'
    'area': '4'
    'name': '京都(椿寺)'
    'star': '4'
    'resource': '冷却材、依頼札'
    'max_lv': '68'
    'sence': ''
  '17':
    'id': '5-1'
    'no': '17'
    'area': '5'
    'name': '鎌倉'
    'star': '3'
    'resource': '木炭'
    'max_lv': '78'
    'sence': ''
  '18':
    'id': '5-2'
    'no': '18'
    'area': '5'
    'name': '元寇(博多湾)'
    'star': '4'
    'resource': '冷却材、木炭、玉鋼'
    'max_lv': '82'
    'sence': ''
  '19':
    'id': '5-3'
    'no': '19'
    'area': '5'
    'name': '墨俣(承久の乱)'
    'star': '5'
    'resource': '砥石・玉鋼'
    'max_lv': '88'
    'sence': ''
  '20':
    'id': '5-4'
    'no': '20'
    'area': '5'
    'name': '阿津賀志山(厚樫山)'
    'star': '5'
    'resource': '木炭、冷却材'
    'max_lv': '99'
    'sence': ''
